using UnityEngine;

public class BulletScript : MonoBehaviour
{
    public float Speed;
    private Rigidbody2D Rigidbody2D;
    private Vector2 Direction;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Rigidbody2D = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    private void FixedUpdate()
    {
        Rigidbody2D.linearVelocity = Direction * Speed;
    }
    
    public void SetDirection(Vector2 direction)
    {
        Direction = direction;
    }
    
    public void DestroyBullet()
    {
       Destroy(gameObject);
    }
}
